### ISSUE TITLE
How to best describe what mk does in a single sentence?

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/mk#126]
As `mk` is clearly not yet-another-build-tool and it does not replace any other tool, it is little bit hard to describe it.

## What it does

- detects project own build tools
- allows user to easily run exposed test/build commands
- minimize the keystrokes needed for running these commands
- reports if a required build tool is missing
- it is very easy to extend
- it has zero configuration (at least for now) as its configuration is basically loaded from detected tools

Any single-sentence suggestion to describe what `mk` is would be more than welcomed, we need such description. Waiting for suggestions...

**Comment by Slackadays** [comment]
Become a wizard in open-source (?) contribution in no time with `mk`. (Why)

`mk` makes it really easy to contribute to any project out there. (How)

`mk` lets you run any command that you might use with other software projects. (What)
