### ISSUE TITLE
Add CMake support and some thoughts

### ISSUE THREAD

**Issue by Slackadays** [pycontribs/mk#135]
I just wanted to say that `mk` is really cool, but there are a couple things I wanted to mention:

- [ ] There should be CMake support because many projects use it and it's tricky to use for beginners, but there are a few patterns that you can follow, such as a `build` directory and `CMakeLists.txt` being present
- [x] `mk` shouldn't try to execute .so files, as it provided the option to do so, but only the glibc .so system libraries can actually work this way.
- [x] `mk` should inform you if `up` won't work before you actually use it, as it never mentioned that I need to be in a non-default branch to use `up` when running `mk`

Overall, I think `mk` has some serious potential. :)

**Comment by ssbarnea** [comment]
@Slackadays All good points. Now it would be very useful if you can also include links to some projects where these issues occur, so I can test the fixes for them.

**Comment by ssbarnea** [comment]
@Slackadays Can you give me a link to a cmake using repo that is not too big? Cloning mysql is far from being a pleasure, so I would prefer to test with one that is smaller, but still actively maintained.

**Comment by Slackadays** [comment]
@ssbarnea Sorry I didn't see your comment earlier, but one such repo is actually my Clipboard project here: https://github.com/Slackadays/Clipboard and another one is https://github.com/WerWolv/ImHex.

**Comment by ssbarnea** [comment]
How can I identify cmake targets/command that I need to expose? Detecting the presence of the config file is easy but... last time I used cmake was like 15+ years ago. Gime me some hints and I will write the support for it.

**Comment by Slackadays** [comment]
You'll need to first configure a CMake project, which means invoking `cmake` with the location of the CMakeLists.txt file after it. For example, if CMakeLists.txt is in the same directory, do `cmake .`. The trick for Clipboard is knowing to add `-DCMAKE_BUILD_TYPE=MinSizeRel` at the end, which unfortunately almost means to make this work in general for other CMake projects, you'll need to make an AI trained on documentation. To build the projects, just do `cmake --build` with the location of the configuration files you made in the first step following that command. So for example, if you don't change directories after doing `cmake .`, then you'll do `cmake --build .` Finally, to install, most projects have an `install` target which is the same as `build`, or just `cmake --install .`.

**Comment by Slackadays** [comment]
Something to consider is that most CMake projects have specific instructions because CMake is so flexible, and the documentation will tell you exactly how to follow those specific instructions. Unfortunately, if you want `mk` to save you from reading documentation, this goes back to an AI that can read the docs and figure out the right commands.

**Comment by ssbarnea** [comment]
This means that the support for cmake will be be minimal, only detecting that the project needs cmake and if cmake is installed. I am not planning to involve documentation parsing or AI, yet.

That seems to be a big design flaw in cmake but considering its age, I am not surprised it shares that same UX-traits as make ;)
